# -*- coding: utf-8 -*-
"""DATA SCIENCE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hRsv3SX7ZsQPAp5yjQ2T9dZe5yryfRka

primitive /basic data types

PRIMITIVE DATA TYPES
"""

a=10
b=12.6
c=2+3j
d="python"
e=True

type(a)

type(b)

type(c)

type(e  )

id(a)



"""there are different types of operators
assignment operator(=)
"""

a=10
b=12
c=7

d=a+b #addition
e=a-b #subtraction
f=c//b #floor division
g=b%c  #modulus
print(d,e,f,g)

"""Arithmetic Operators:
+ (add), - (subtract), * (multiply), / (divide), // (floor divide), % (modulus), ** (power)

Comparison Operators:
== (equal), != (not equal), > (greater), < (less), >= (greater or equal), <= (less or equal)

Logical Operators:
and (both true), or (one true), not (negates)

Assignment Operators:
=, +=, -=, *=, /=, %=, **=, //=

Bitwise Operators:
& (AND), | (OR), ^ (XOR), ~ (NOT), << (left shift), >> (right shift)

Membership Operators:
in, not in

Identity Operators:
is, is not

#strings
+any thing is defined in "" ''
+immutabble/notchangeble
"""

r="right now i was learning how slicing in pythn works"

r

r[3]

r[:]

r[:10]#it will give until 9 it wont proint 10th place

r[::-1]

len(r)

r.upper()

r.lower()

s="bull shit"
r+s

r*4

#type casting
a=input()

type(a)

a=int(input("7"))

type(a)

chr(8)

r.split()

#if else
a=int(input("entera="))
if a%2==0:
  print("a is even")
else:
  print("a is odd")
print("thankyou")

a=int(input("entera="))
if a%2==0:
  print("a is even")
else:
  print("a is odd")
print("thankyou")

i=1
while i<=10:
  print(i,end="\t")
  i=i+1

i=(6)
while i<=10:
  print(i)
  i=i+1

i=1
while i<=10:
  if i%2==0:
    print(i)

  i=i+1

i=1
while i<=30:
  print(i,end="\t")
  i=i+2

i=1
while i<=10:

  if i%3==0:
    print(i)
  i=i+1

for i in range(5):
    print(i)   # prints 0 to 4

for i in range(2):
    for j in range(3):
        print(i, j)

num = 12345
rev = 0

while num > 0:
    digit = num % 10
    rev = rev * 10 + digit
    num //= 10

print("Reversed number:", rev)

num = 121
temp = num
rev = 0

while num > 0:
    digit = num % 10
    rev = rev * 10 + digit
    num //= 10

if temp == rev:
    print("Palindrome number")
else:
    print("Not a palindrome")

for i in range(1,10):
  print(i,end='\t')

for i in range(1,7,2):
  print(i)

for i in range(1,50):
  if i%2==0:
    print(i,end="\t")

for i in range(1,10):
  for j in range(3,7):
     print(i,j)

for i in range(1,7):
  print("+++"*i)

"""# **DATA STRUTURES **
LIST TUPLE SET DICTIONARY

+Any thing specified in []
+ist attribute separarted with comma ,
+mutable changeable,
+ordered collection of items,
+hetrogenous/compound data types.
"""

#nested slicing
  y=["coming",["tothe",["point.B1B2B3",["GENUIINE"]]]]

y[0]

y[0][5]

y[1]

y[1][1]

y[1][1][1]

y[1][1][1][0]

y[1][1][1][0][6]

y[1][1][1][0][::-1]

l=[1,2,3,4,5]

l[::-1]

len(l)

"""## list functions

append(),extend,insert(),pop(),remove(),clear(),del(),max,min,sum,sort,sorted()
"""

l+[7,9,10]

l*3

l.append([55,56])#helps to add only end of element not list

l

l.extend([8,9,10])#helps to add more than one
l

l.insert(1,88)#ineser in specific place
l

l.insert(2,[34,35])
l

l.pop()#if youndont assign it will remove last number by default

l.pop(4)#it will remove index 4 from the list

l

l.remove(0)

l

l.pop(1)

l

l.pop(1)

l

"""# tuples

anything defind in (),immutable and not changeable,ordered collection,hetrogenous compound data types
"""

t=(1,2,3,"mouli",'mogli')

type(t)

t[2]

t[3]

t[3][3]

"""# sets

separated by comma,unordered collection,duplicates not allowed
+ mutable cahngebale
+ set{}
"""

#here instead of extend() we use update()

s={1,2,3,4,4,5,6,7}

s#no dup;icates allowed

#mutable and changeble
s.add(10)
s

s.update({11,12,13})

s

s.discard(11)#we use discard instead of remove
s

s.pop()

"""# DICTIONARY
+ {}
+ KEYVALUE PAIRS PRESENT
+ KEY AND VALUES ARE PRESENTED BY:
+ MUTABLE CHANGEABLE

"""

o={"cars":2,"buses":7,"owls":10}

type(o)

o.keys()

o.values()

o.items()

o["buses"]=6#replace key values
o

o.get("owls")

#we can use update () to add any key value pairs
o.update({"horses":9,"lion":19})

o

del(o[9])
o

o.clear()

o

#loops
#how to create dat structures dynamically

#eval
eval("65-2+3")

s="pandu.420"
for i in s:
  print(i,end="\t")

for i in range(10):
  if i==5:
    break
  print(i)

len(s)

for i in range(len(s)):
  print(i)

l=[1,2,3,4,5,6]
i=0
while i<len(l):
  if i%2==0:
     print(l[i])
  i=i+1

l=[1,2,3,4,5,6]
i=0
while i<len(l):
  print(l[i])
  i=i+1

#how to create as dynamically
l=[]
for i in range(1,10):
  l.append(i)
print(l)

a=[]
b=[]

for i in l:
  if i%2==0:
    a.append(i)
  else:
    b.append(i)
print(a,b)

sqr=[]
for i in l:
  sqr.append(i**2)
print(sqr)

l=["tarak", "rama" ,"rajesh" ]
r=[]
i=0
for i in l:
  r.append(i[:2])
print(r)

r=[]
for i in l:
  r.append(i[::-1])
r



"""# def function syntax
+ def fname(parameters): #formal/dummy parameters
  + statement(s)
  + return statement(s)
"""

def wishme():
  print("shut the fuck up")

wishme()

def another(p="common"):
  print("i dont give a fuck qbout you",p)
another()

another("hell")

#types of functions
#required/positional
#default arguements
#keword arguements
#variable ;enghth arguements
#keyword variabe length arguements

def sub(a,b):
  c=a-b
  return c

sub(2,b=1)

sub(1,2)

sub(a=1,2) #we have to gidenote  b

def sub(a=12,c=90):
  y=a*c
  return y

sub()

sub(12,c=9)

sub(12,19)

sub(12)

#variable length arguements
def vlen(*a):
  print(type(a))
  print(a)

vlen(1,2,3,4)

#keyword variable for variable length argumenets
def add(*a):
  s=0
  for i in a:
    s=s+i

  return s

add(1,2,3,4,5,6,7,8,8,10)

#keyworf variable length arguemens
def fname(**a):
  print(type(a))
  print(a)

fname(a=3,k=19)

"""# Different ways to import module"""

import math

math.sqrt(8)

math.factorial(10)

import numpy

import math as m

m.sin(45)

m.radians(45)

import statistics as sam
sam.mean([1,2,3,6,5,6])

a=[1,2,34,5,5,6,7,4,5]
sam.mode(a)

from statistics import mean as m1,median as m2# other way

m1(a),m2(a)

import random as r
r.choice(a)

r.randint(1,8)

5%2

5/2

5//2

for i in range(10):
   a="+"*i+"fu"
   print(a)

a

b



"""# NUMPY"""

import numpy as np

a=np.array(range(1,10))

a

np.arange(1,10) #we can use this way as shortly

a.reshape(3,3)

a.resize(3,3)

a

np.arange(1,17).reshape(4,4)

a

np.arange(20).reshape(2,2,5)

np.linspace(1,10,10)#last 10 icludes 10 intervals

np.linspace(1,11,100)

np.empty([3,3])

np.zeros([4,4],dtype="float")

np.ones([5,3,3],dtype="int")

np.eye(6,dtype="int")

np.identity(5)

a

a.transpose()

np.random.rand(7)#it will give randomly between 0 t0 1

np.random.rand(3,5)

np.random.randint(1,6)

np.random.randint(1,100,5)#it will give randomly 5 numbers

a=np.arange(1,10).reshape(3,3)
b=np.arange(11,20).reshape(3,3)


a,b

a

b

a*3

a/3

a+b

a*b

a*-4

a+2

a.max()

a.min()

a.sum()

np.zeros((3,3))      # 3x3 of 0

np.arange(1, 10, 2)  # 1 to 9 with step 2

np.linspace(1, 5, 100000) # 5 numbers evenly space

a.flatten()

arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

np.mean(arr2)

"""import numpy as np"""

import numpy as np

a=np.arange(1,17).reshape(4,4)

print(a)

a[2,1] #2nd row 1st column here rows starts from 0,1,2,3

a[:,0]

a[:,3] #all of 3 rd column

a[2,:]

a[:,3].reshape(2,2)

a[:1]# 0 th row

a[:2]#0,1 th row

a[:,::-1]

a[::-1,::-1]

a[:,::1]

a[:,1]



a[:2]

a[:,2]

a[:2,:2]

"""MATPLOTLIB"""

import matplotlib.pyplot as plt
print(dir(plt))

x=[1,2,3,4]
y=[4,7,8,9]
plt.plot(x,y)
x=[1,2,3,4]
y=[4,7,8,9]
plt.title("uygyuhihugyfchgj")

y=[2,8,6,19]
plt.plot(x,y) # if we dont mentio x bydefault it ttajw values

plt.xlabel("distance")
plt.ylabel("dpeed")
x=[1,2,3,4,5]
y=[4,8,45,40,9]
plt.plot(x,y,"r")
plt.grid()
plt.title("distance vs speed")
plt.show()

plt.xlabel("distance")
plt.ylabel("dpeed")
x=[1,2,3,4,5]
y=[4,8,45,40,9]
plt.plot(x,y,"_")
plt.grid()
plt.title("distance vs speed")
plt.show()

days=range(1,6)
cel_max=[12,14,15,17,34]
cel_min=[12,15,61,12,34]
plt.xlabel("Days")
plt.ylabel("temp im degree celsius")
plt.title("days vs celsius")
plt.plot(days,cel_max,"y")
plt.plot(days,cel_min,"b")
plt.show()

days=range(1,6)
cel_max=[12,14,15,17,34]
cel_min=[12,15,61,12,34]
plt.xlabel("Days")
plt.ylabel("temp im degree celsius")
plt.title("days vs celsius")
plt.plot(days,cel_max,"b",label="max")
plt.plot(days,cel_min,"y",label="min")
plt.legend(loc="lower right")#it displays labelsmin max in lower location
plt.show()

import numpy as np
x=np.linspace(0,2*np.pi,50)#it will give 50 valies betw [0,2pi]
f=np.sin(x)
plt.plot(x,f)

np.sin(1)

import numpy as np
x=np.linspace(0,2*np.pi,50)
f=np.sin(x)
u=np.cos(x)
t=np.tan(x)
plt.plot(x,f,"r",label="sin graph")
plt.plot(x,u,"b",label="cos graph")
plt.legend(loc="lower right")

plt.show()

f1=3*np.sin(x)
f2=7*np.sin(2*x)
f3=0.3*np.sin(x)
f4=2*np.cos(x)
plt.plot(x,f1,color="blue",label="sinx")
plt.plot(x,f2,color="green",label="cosx")
plt.plot(x,f3,color="red",label="sinx")
plt.plot(x,f4,color="grey",label="tanx")
plt.legend()
plt.show()

plt.bar([1,2,3,4,5,6],[12,13,45,34,45,89],label="ex1")
plt.bar([7,8,9,15,13],[18,2,34,23,45],label="ex2")
plt.xlabel("views")
plt.ylabel("money")
plt.title("views vs money")
plt.legend()
plt.show()

#pie chart graph
slices=[7,2,2,13]#splitiing 24 hrs
activities=["sleeping","eatimg","reading","playind"]
cols=["c","m","b","g"]
plt.pie(slices,labels=activities,colors=cols,startangle=90,explode=[0,0,0,0],autopct="%1.1f%%")
plt.plot()

import matplotlib.pyplot as plt
x=[1,2,3,4,5]
y=[2,4,5,6,7]
plt.scatter(x,y)
plt.show()

import pandas as pd
import numpy as np

l=[10,20,30]
labels=["a","d","c"]
arr=np.array(l)

arr

pd.Series(l) #Series(data,index,dtype)

pd.Series(data=l,index=labels)

import pandas as pd
import numpy as np
l=[10,20,30]
labels=["a","d","c"]
arr=np.array(l)
pd.Series(l,labels)

pd.Series(data=l,index=range(30,33),dtype="float32")

d={"e":19,"u":89,"g":92}
pd.Series(d)

se1=pd.Series([1,2,3,4],index=["comrade","pak","china","communist"])

se2=pd.Series([1,2,5,4],index=["comrade","eng","china","communist"])

se1

se2

se1["pak"]

se1+se2

x="p a n d u".split()

x

"""DATA FRAME"""

#dataframe
from numpy.random import randn
np.random.seed(101)
df=pd.DataFrame(randn(5,4),index="A B C D E".split(),columns="W X Y Z".split())

df

df['W']

df[["W",'Y']]

df['new']=df["W"]+df["Z"]

df

df.drop("new",axis=1) # axis=1 means removes column

#df.drop("new",axis=1) # axis=1 means removes column
df

df.loc["B":"D"]

df.loc['B','X']#to print specific location

df.reset_index()

newindex="te pa ka ap tn".split()

newindex

df["states"]=newindex

df

df.set_index('states',inplace=True)

df#it repace index values as states

df=pd.DataFrame({'A':[1,1,np.nan],'B':[5,np.nan,np.nan],'c':[1,2,3]})

df

df.dropna()#it will remove the values nan from row

df.dropna(axis=1)#remov na values from columns

df

df.fillna(value="fillvalue")

df["A"].fillna(value=df['A']).mean()

import pandas as pd

df={"company":['google','google','infy','infy','tcs','tcs'],"person":['naveen','chandu','hindu','paddu','ram','rayudu'],"sales":[122,134,432,123,345,333]}

pd.DataFrame(df)

df["company"]

type(df)

bycomp=df.groupby("company")

df=pd.DataFrame({'col1':[1,2,3,4],"col2":[555,333,444,555],"col3":['abc','def','fgh','uio']})

df

df['col2'].unique()

df["col2"].nunique()

#DATA PREPROCESSING

"""**DATA PREPROCESSING***"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data=pd.read_csv("/content/drive/MyDrive/Salary_Dataset_DataScienceLovers.csv")

x=data.iloc[:,:-1].values

x

y=data.iloc[:,1:2].values

y

